# Generated by Django 4.2.19 on 2025-03-09 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='surgery_type',
            field=models.CharField(choices=[('intertro', 'intertrochanteric fracture'), ('moz', 'moz')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='warning_signs',
            field=models.TextField(blank=True, default=''),
        ),
    ]
