# Generated by Django 4.2.19 on 2025-03-11 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_alter_user_surgery_type_alter_user_warning_signs'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='سن'),
        ),
        migrations.AlterField(
            model_name='user',
            name='daronum',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='کد رهگیری دارو'),
        ),
        migrations.AlterField(
            model_name='user',
            name='doctor',
            field=models.CharField(blank=True, choices=[('dr_zandi', 'دکتر زندی')], max_length=20, null=True, verbose_name='دکتر معالج'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='مدیر'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='medication_instructions',
            field=models.TextField(blank=True, default='', verbose_name='دستورات دارویی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='national_id',
            field=models.CharField(max_length=10, unique=True, verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='next_visit',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='تاریخ ویزیت بعدی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nutrition',
            field=models.TextField(blank=True, default='', verbose_name='توصیه\u200cهای تغذیه\u200cای'),
        ),
        migrations.AlterField(
            model_name='user',
            name='outpatient_services',
            field=models.TextField(blank=True, default='', verbose_name='خدمات سرپایی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='رمز عبور'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True, verbose_name='شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='user',
            name='self_care_recommendations',
            field=models.TextField(blank=True, default='', verbose_name='توصیه\u200cهای خود مراقبتی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='surgery_type',
            field=models.CharField(blank=True, choices=[('intertro', 'جراحی اینترتروکانتریک'), ('brain', 'جراحی مغز')], max_length=20, null=True, verbose_name='نوع عمل'),
        ),
        migrations.AlterField(
            model_name='user',
            name='warning_signs',
            field=models.TextField(blank=True, default='', verbose_name='علائم هشدار'),
        ),
    ]
